grafana:
  plugins:
    - https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/releases/download/v1.10.0/mahendrapaipuri-dashboardreporter-app-1.10.0.zip;mahendrapaipuri-dashboardreporter-app
    - grafana-image-renderer
  env:
    GF_REPORTER_PLUGIN_APP_URL: "http://prometheus-grafana.monitoring.svc:80"

    GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: mahendrapaipuri-dashboardreporter-app
    GF_REPORTER_PLUGIN_REMOTE_CHROME_URL: "ws://0.0.0.0:9223"
    # GF_REPORTER_PLUGIN_NATIVE_RENDERER: "false" 
    # GF_FEATURE_TOGGLES_ENABLE and GF_AUTH_MANAGED_SERVICE_ACCOUNTS_ENABLED must be defined 
    GF_FEATURE_TOGGLES_ENABLE: accessControlOnCall,idForwarding,externalServiceAccounts
    # must be true for Grafana v11.3.0+ 
    # GF_AUTH_MANAGED_SERVICE_ACCOUNTS_ENABLED: "true"  # must be true for Grafana v11.3.0+

    # --- log levels
    # GF_LOG_LEVEL: "debug"
    # GF_LOG_FILTERS: rendering:debug plugin.mahendrapaipuri-dashboardreporter-app:debug
    
    # --- reporter settings
    GF_REPORTER_PLUGIN_SKIP_TLS_CHECK: "true"
    GF_REPORTER_PLUGIN_REPORT_THEME:  "light"
    GF_REPORTER_PLUGIN_REPORT_ORIENTATION:  "landscape"
    GF_REPORTER_PLUGIN_REPORT_LAYOUT:  "grid"
    GF_REPORTER_PLUGIN_REPORT_TIMEZONE:  "Europe/Istanbul"

  extraContainers: |
    - name: headless-chrome
      image: chromedp/headless-shell:132.0.6793.2
      args:
        - --no-sandbox
        - --headless
        - --disable-gpu
        - --use-gl=swiftshader
        - --use-angle=swiftshader
        - --enable-unsafe-swiftshader # This flag addresses the WebGL deprecation warning
        - --remote-debugging-address=0.0.0.0
        - --remote-debugging-port=9223
        - --user-data-dir=/tmp/chrome_data
        - --disable-setuid-sandbox
        - --disable-background-timer-throttling
        - --disable-backgrounding-occluded-windows
        - --disable-renderer-backgrounding
        - --disable-features=TranslateUI
        - --disable-ipc-flooding-protection
        - --font-render-hinting=none
        - --single-process # Eliminates renderer process issues
        - --disable-zygote # Disables zygote process management
      env:
        - name: FONTCONFIG_PATH
          value: "/tmp/.fontconfig"
        - name: XDG_CACHE_HOME
          value: "/tmp/.cache"
        - name: XDG_CONFIG_HOME
          value: /tmp/.chromium
        - name: XDG_CACHE_HOME
          value: /tmp/.chromium

      securityContext:
        runAsUser: 1000 # Use a non-root user
        capabilities:
          add:
            - SYS_ADMIN  # Allows OOM score adjustment
            - SYS_PTRACE  # Sometimes sufficient for process management
      ports:
        - containerPort: 9222
          protocol: TCP
        - containerPort: 9223
          protocol: TCP
      volumeMounts:
        - name: dshm-chrome
          mountPath: /dev/shm


  ## Additional Grafana server volumes
  extraVolumes:
    - name: dshm-chrome
      emptyDir:
        medium: Memory
        sizeLimit: 2Gi
    - name: chrome-cache
      emptyDir: {}
    - name: fontconfig-cache
      emptyDir: {}

  imageRenderer:
    enabled: true
    replicas: 1
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPU: "60"
      targetMemory: ""
      behavior: {}
    resources:
      # limits:
      #   cpu: 100m
      #   memory: 100Mi
      requests:
        cpu: 1024m
        memory: 2048Mi
    # The url of remote image renderer if it is not in the same namespace with the grafana instance
    serverURL: ""
    # The callback url of grafana instances if it is not in the same namespace with the remote image renderer
    renderingCallbackURL: ""
    env:
      HTTP_HOST: "0.0.0.0"
      # Fixes "Error: Failed to launch the browser process!\nchrome_crashpad_handler: --database is required"
      # XDG_CONFIG_HOME: /tmp/.chromium
      # XDG_CACHE_HOME: /tmp/.chromium

      # https://grafana.com/docs/grafana/latest/setup-grafana/image-rendering/#configuration
      # --- ÖNEMLİ -- PERFORMANS AYARLARI
      # RENDERING_MODE: clustered
      # Recommendation of grafana-image-renderer for optimal performance
      # https://grafana.com/docs/grafana/latest/setup-grafana/image-rendering/#configuration
      RENDERING_MODE: clustered
      # RENDERING_CLUSTERING_MODE: context
      RENDERING_CLUSTERING_MODE: browser
      RENDERING_CLUSTERING_MAX_CONCURRENCY: 5
      RENDERING_CLUSTERING_TIMEOUT: 600
      IGNORE_HTTPS_ERRORS: true
      GF_REPORTER_PLUGIN_NATIVE_RENDERER: "false" 
      BROWSER_TZ: Europe/Istanbul
      RENDERING_ARGS: '--no-sandbox,--disable-setuid-sandbox,--remote-debugging-port=9223'
      DEBUG: 'puppeteer-cluster:*'
      XDG_CONFIG_HOME: /tmp/.chromium
      XDG_CACHE_HOME: /tmp/.chromium

    securityContext:
      capabilities:
        add:
          - SYS_ADMIN  
          - SYS_PTRACE 
        drop: []